<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepositoryNew extends EntityRepository
{
    public function getAllArticles(){
        $qb = $this->createQueryBuilder('a')
            ->select(['a.title,a.id,au.name as authorName'])
            ->innerJoin('a.author','au');

        return $qb->getQuery();
    }

    public function getLastArticles($nbOfArticles, $tagName = null){
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->orderBy('a.createdAt', 'desc')
            ->setMaxResults($nbOfArticles);
        if (empty($tagName)){
            $query = $qb->getQuery();
        } else {
            $qb->innerJoin('a.tags','t')
                ->where('t.tagName = :tagName');
            $query = $qb->getQuery();
            $query->setParameter('tagName', $tagName);
        }

        return $query;
    }

    public function getArticlesByTagName($tag){
        $qb = $this->createQueryBuilder('a')
            ->select('a.title, a.id, au.name as authorName')
            ->innerJoin('a.author','au')
            ->innerJoin('a.tags', 't')
            ->where('t.tagName = :tagName');
        $query = $qb->getQuery();
        $query->setParameter('tagName', $tag);

        return $query->getArrayResult();
    }
}
