app:
    resource: '@AppBundle/Controller/'
    type: annotation

login_admin_check:
  path: /admin/login-check

logout_admin:
  path: /admin/logout

login_author_check:
  path: /author/login-check

logout_author:
  path: /author/logout